dependencies {

  // Spring Boot Starters
  implementation 'org.springframework.boot:spring-boot-starter-web'
  implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
  implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

  // Spring Security
  implementation 'org.springframework.boot:spring-boot-starter-security' 
  implementation 'org.springframework.boot:spring-boot-starter-validation'

  // MySQL
  implementation 'mysql:mysql-connector-java:8.0.33'

  // Lombok
  compileOnly 'org.projectlombok:lombok'
  annotationProcessor 'org.projectlombok:lombok'

  // Test
  testImplementation 'org.springframework.boot:spring-boot-starter-test'
  testImplementation 'org.springframework.security:spring-security-test'
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	

  // Thymeleaf
  // 스프링 시큐리티 기능을 사용하기 위한 라이브러리
  implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'
  // 레이아웃 다이얼렉트
  implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect'

}
