server:
  port: 8086
  tomcat:
    max-http-form-post-size: 50MB
    max-swallow-size: 50MB

spring:
  profiles:
    include: secret
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB       
      max-request-size: 20MB    # 한 번의 요청에 포함된 전체 데이터 크기

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true